// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMTuC7koB8XFH1xCVijT2M4M6PQktI-I',
    appId: '1:555059719053:web:d479be4373a618176debc4',
    messagingSenderId: '555059719053',
    projectId: 'testapp-a6b38',
    authDomain: 'testapp-a6b38.firebaseapp.com',
    storageBucket: 'testapp-a6b38.firebasestorage.app',
    measurementId: 'G-7GNSWP88LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvd5xe71eunVMIHXWcOsv5GHOgoY3roxE',
    appId: '1:555059719053:android:bde6f275b923002c6debc4',
    messagingSenderId: '555059719053',
    projectId: 'testapp-a6b38',
    storageBucket: 'testapp-a6b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfApbSvQa-OQMB7lxX8rXf3SWWwlLRgs',
    appId: '1:555059719053:ios:5443695128cd1c576debc4',
    messagingSenderId: '555059719053',
    projectId: 'testapp-a6b38',
    storageBucket: 'testapp-a6b38.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntigration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfApbSvQa-OQMB7lxX8rXf3SWWwlLRgs',
    appId: '1:555059719053:ios:5443695128cd1c576debc4',
    messagingSenderId: '555059719053',
    projectId: 'testapp-a6b38',
    storageBucket: 'testapp-a6b38.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntigration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOMTuC7koB8XFH1xCVijT2M4M6PQktI-I',
    appId: '1:555059719053:web:d1f56cb158a220ea6debc4',
    messagingSenderId: '555059719053',
    projectId: 'testapp-a6b38',
    authDomain: 'testapp-a6b38.firebaseapp.com',
    storageBucket: 'testapp-a6b38.firebasestorage.app',
    measurementId: 'G-XM6YE5JY3E',
  );
}
